create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    num_green_potions integer null,
    num_green_ml integer null,
    gold integer null default 100,
    num_red_potions integer null,
    num_red_ml integer null,
    num_blue_potions integer null,
    num_blue_ml integer null,
    num_dark_ml integer null,
    num_purple_potions integer null,
    num_teal_potions integer null,
    num_slospecial_potions integer null,
    num_dark_potions bigint null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;


  create table
  public.potion_mixes (
    id bigint generated by default as identity not null,
    name text null default ''::text,
    red_amt double precision null,
    green_amt double precision null,
    blue_amt double precision null,
    dark_amt double precision null,
    inventory bigint null default '0'::bigint,
    constraint potion_mixes_pkey primary key (id)
  ) tablespace pg_default;


  create table
  public.cart_line_item (
    cart_id bigint generated by default as identity not null,
    potion_id integer null,
    quantity integer null,
    created_at timestamp with time zone not null default now(),
    constraint cart_line_item_pkey primary key (cart_id)
  ) tablespace pg_default;