create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_ml integer not null default 0,
    gold integer not null default 100,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_inventory (
    id bigint generated by default as identity,
    sku text not null,
    type_red smallint not null,
    type_green smallint not null,
    type_blue smallint not null,
    cost integer not null,
    quantity integer not null,
    type_dark integer not null default 0,
    constraint potion_inventory_pkey primary key (id),
    constraint potion_inventory_id_key unique (id),
    constraint potion_inventory_sku_key unique (sku)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity,
    customer_name text not null,
    created_at timestamp with time zone not null default now(),
    constraint carts_pkey1 primary key (cart_id)
  ) tablespace pg_default;

create table
  public.carts_transactions (
    id bigint generated by default as identity,
    cart_id bigint not null,
    sku text not null,
    quantity integer not null,
    created_at timestamp with time zone not null default now(),
    constraint carts_transactions_pkey primary key (id),
    constraint carts_transactions_cart_id_fkey foreign key (cart_id) references carts (cart_id) on delete cascade,
    constraint carts_transactions_sku_fkey foreign key (sku) references potion_inventory (sku)
  ) tablespace pg_default;

create table
  public.barrels_sessions (
    catalog_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    constraint barrel_catalog_sessions_pkey primary key (catalog_id)
  ) tablespace pg_default;

create table
  public.barrels_catalog (
    barrel_id bigint generated by default as identity,
    sku text not null,
    quantity integer not null,
    constraint barrels_pkey primary key (barrel_id)
  ) tablespace pg_default;

create table
  public.barrels_history (
    id bigint generated by default as identity,
    catalog_id bigint not null,
    barrel_id bigint not null,
    cost integer not null,
    constraint catalog_loggin_pkey primary key (id),
    constraint barrels_history_barrel_id_fkey foreign key (barrel_id) references barrels_catalog (barrel_id),
    constraint barrels_history_catalog_id_fkey foreign key (catalog_id) references barrels_sessions (catalog_id)
  ) tablespace pg_default;