-- To create 'global_inventory' table
create table
  public.global_inventory (
    num_green_ml integer not null,
    gold integer not null,
    primary_key integer generated by default as identity,
    num_blue_ml integer null default 0,
    num_red_ml integer null default 0,
    num_dark_ml integer not null default 0,
    ml_capacity integer not null default 0,
    potion_capacity integer not null default 0,
    increase_ml_capacity boolean null default false,
    increase_potion_capacity boolean null default false,
    constraint global_inventory_pkey primary key (primary_key),
    constraint global_inventory_primary_key_key unique (primary_key)
  ) tablespace pg_default;


-- To create 'carts' table
create table
  public.carts (
    id bigint generated by default as identity,
    customer_name text not null,
    character_class text null,
    level text null,
    created_at timestamp with time zone null default now(),
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;


-- To create 'cart_items' table
create table
  public.cart_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint null,
    potion_id bigint null,
    quantity integer not null default 0,
    constraint cart_items_pkey primary key (id),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint public_cart_items_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;
  

-- To create 'potions' table
create table
  public.potions (
    id bigint generated by default as identity,
    sku text not null,
    num_potions integer not null,
    price integer not null,
    parts_red integer not null,
    parts_green integer not null,
    parts_blue integer not null,
    parts_dark integer not null,
    priority integer null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;

  -- To create 'potions_inventory' table
  create table
  public.potions_inventory (
    id bigint generated by default as identity,
    sku text not null,
    num_potions integer not null,
    created_at timestamp with time zone null default (now() at time zone 'pst'::text),
    order_id integer null,
    constraint legerized_potions_pkey primary key (id)
  ) tablespace pg_default;

  -- To create 'potions_catalog' table
  create table
  public.potions_catalog (
    id bigint generated by default as identity,
    sku text not null,
    price integer not null,
    parts_red integer not null,
    parts_green integer not null,
    parts_blue integer not null,
    parts_dark integer not null,
    priority integer null,
    constraint potions_catalog_pkey primary key (id)
  ) tablespace pg_default;

  -- To create 'legerized_inventory' table
create table
  public.ledgerized_inventory (
    num_green_ml integer not null,
    gold integer not null,
    primary_key integer generated by default as identity,
    num_blue_ml integer null default 0,
    num_red_ml integer null default 0,
    num_dark_ml integer not null default 0,
    order_id integer null,
    created_at timestamp with time zone null default (now() at time zone 'pst'::text),
    order_type text null,
    constraint legerized_inventory_pkey primary key (primary_key),
    constraint legerized_inventory_primary_key_key unique (primary_key)
  ) tablespace pg_default;

  -- To create 'shop_states' table
  create table
  public.shop_states (
    id bigint generated by default as identity,
    ml_capacity integer null default 10000,
    potion_capacity integer null default 50,
    increase_ml_cap boolean null default false,
    increase_potion_cap boolean null default false,
    constraint shop_states_pkey primary key (id)
  ) tablespace pg_default;